Add controllers
SnezhanaB/java-shareit pull request #1
Opened 2024-04-15 16:47 UTC by SnezhanaB

2024-04-16 10:33 UTC, kriwsha requested changes

2024-04-16 10:33 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    // private int ownerId;
Закомментированный код следует удалять

2024-04-16 10:33 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    public static ItemDto toItemDto(Item item) {
Я бы рекомендовал подобные методы выносить в отдельные мапперы

2024-04-16 10:33 UTC, kriwsha commented on src/main/resources/schema.sql
> +--CREATE TABLE IF NOT EXISTS users (
Здесь также следует удалить закомментированные скрипты

2024-04-16 10:33 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    public static UserDto toUserDto(User user) {
Здесь также я бы рекомендовал вынести в отдельный класс маппер. Этот метод не зависит от внутреннего устройства класса, поэтому смешивать логику мапера и модели не следует

2024-04-17 05:23 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public static BookingDto toBookingDto(Booking booking) {
Все таки было бы здорово все подобные методы перенести в маппер

2024-04-17 05:23 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    public static ItemRequestDto toItemRequestDto(ItemRequest request) {
И здесь

2024-04-17 09:18 UTC, SnezhanaB commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public static BookingDto toBookingDto(Booking booking) {
Убрала, в будущем они не понадобятся

2024-04-22 17:58 UTC, merged